name: CustomJoinMessages
version: ${version}
main: net.insprill.cjm.CJM
api-version: 1.13
author: Insprill
description: The most advanced custom join messages plugin on the market.

softdepend:
  - AuthMe
  - CMI
  - PlaceholderAPI
  - PremiumVanish
  - SuperVanish
  - Vault

commands:
  cjm:
    description: Base command for Custom Join Messages.

permissions:
  cjm.default:
    default: true
