name: CustomJoinMessages
version: ${version}
main: net.insprill.cjm.CustomJoinMessages
api-version: 1.13
author: Insprill
description: The most advanced custom join messages plugin on the market.

softdepend:
  - AuthMe
  - CMI
  - Essentials
  - LockLogin
  - PlaceholderAPI
  - PremiumVanish
  - SuperVanish
  - VanishNoPacket
  - Vault

permissions:
  cjm.default:
    default: true
