name: CustomJoinMessages
version: ${version}
main: net.insprill.cjm.CustomJoinMessages
api-version: 1.13
folia-supported: true
author: Insprill
description: The most advanced custom join messages plugin on the market.

softdepend:
  - AdvancedVanish
  - AuthMe
  - CMI
  - Essentials
  - PlaceholderAPI
  - PremiumVanish
  - SayanVanish
  - SuperVanish
  - VanishNoPacket
  - Vault
  - VelocityVanish
  - Retention # Retention is the plugin loader for Phoenix
  - Phoenix

permissions:
  cjm.default:
    default: true
