blank_issues_enabled: false
contact_links:
  - name: "Wiki"
    url: "https://cjm.insprill.net"
    about: "Unsure how something works? Check out the wiki which most likely has the answer to your question."
